# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0e6c0663-3869-4007-9dd4-f2d88de66e11";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/0e6c0663-3869-4007-9dd4-f2d88de66e11";
      fsType = "btrfs";
      options = [ "subvol=@nixhome" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/0e6c0663-3869-4007-9dd4-f2d88de66e11";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/steam" =
    { device = "/dev/disk/by-uuid/0e6c0663-3869-4007-9dd4-f2d88de66e11";
      fsType = "btrfs";
      options = [ "subvol=steam" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/B9D3-C76F";
      fsType = "vfat";
    };

  swapDevices = [ 
    { device = "/swap/swapfile";
    }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp9s0.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
